//
//  ElementsPropagatorResources.swift
//  SatelliteForecastApp
//
//  Created by Ben Lu on 4/2/22.
//

import Foundation

/// The data generated by elements propagator, including satellite pass / snapshot information.
public struct ElementsPropagatorResources {
    /// A mapping from NORAD ID to the satellite state.
    public var satelliteTrails: [UInt: SatelliteTrails]

    public init(satelliteTrails: [UInt : SatelliteTrails] = [:]) {
        self.satelliteTrails = satelliteTrails
    }
}

extension ElementsPropagatorResources: Equatable {}
