//
//  Owner.swift
//  SatelliteCatalog
//
//  Created by Ben Lu on 6/23/21.
//

import Foundation

public struct Owner: Sendable {
    public init(code: String) {
        self.code = code
    }

    public let code: String

    public var fullName: String? {
        switch code {
        case "AB": return "Arab Satellite Communications Organization"
        case "ABS": return "Asia Broadcast Satellite"
        case "AC": return "Asia Satellite Telecommunications Company (ASIASAT)"
        case "ALG": return "Algeria"
        case "ANG": return "Angola"
        case "ARGN": return "Argentina"
        case "ASRA": return "Austria"
        case "AUS": return "Australia"
        case "AZER": return "Azerbaijan"
        case "BEL": return "Belgium"
        case "BELA": return "Belarus"
        case "BERM": return "Bermuda"
        case "BGD": return "Peoples Republic of Bangladesh"
        case "BHUT": return "Kingdom of Bhutan"
        case "BOL": return "Bolivia"
        case "BRAZ": return "Brazil"
        case "BUL": return "Bulgaria"
        case "CA": return "Canada"
        case "CHBZ": return "China/Brazil"
        case "CHLE": return "Chile"
        case "CIS": return "Commonwealth of Independent States (former USSR)"
        case "COL": return "Colombia"
        case "CRI": return "Republic of Costa Rica"
        case "CZCH": return "Czech Republic (former Czechoslovakia)"
        case "DEN": return "Denmark"
        case "ECU": return "Ecuador"
        case "EGYP": return "Egypt"
        case "ESA": return "European Space Agency"
        case "ESRO": return "European Space Research Organization"
        case "EST": return "Estonia"
        case "EUME": return "European Organization for the Exploitation of Meteorological Satellites (EUMETSAT)"
        case "EUTE": return "European Telecommunications Satellite Organization (EUTELSAT)"
        case "FGER": return "France/Germany"
        case "FIN": return "Finland"
        case "FR": return "France"
        case "FRIT": return "France/Italy"
        case "GER": return "Germany"
        case "GHA": return "Republic of Ghana"
        case "GLOB": return "Globalstar"
        case "GREC": return "Greece"
        case "GRSA": return "Greece/Saudi Arabia"
        case "GUAT": return "Guatemala"
        case "HUN": return "Hungary"
        case "IM": return "International Mobile Satellite Organization (INMARSAT)"
        case "IND": return "India"
        case "INDO": return "Indonesia"
        case "IRAN": return "Iran"
        case "IRAQ": return "Iraq"
        case "IRID": return "Iridium"
        case "ISRA": return "Israel"
        case "ISRO": return "Indian Space Research Organisation"
        case "ISS": return "International Space Station"
        case "IT": return "Italy"
        case "ITSO": return "International Telecommunications Satellite Organization (INTELSAT)"
        case "JPN": return "Japan"
        case "KAZ": return "Kazakhstan"
        case "KEN": return "Republic of Kenya"
        case "LAOS": return "Laos"
        case "LKA": return "Democratic Socialist Republic of Sri Lanka"
        case "LTU": return "Lithuania"
        case "LUXE": return "Luxembourg"
        case "MA": return "Morroco"
        case "MALA": return "Malaysia"
        case "MEX": return "Mexico"
        case "MMR": return "Republic of the Union of Myanmar"
        case "MNG": return "Mongolia"
        case "NATO": return "North Atlantic Treaty Organization"
        case "NETH": return "Netherlands"
        case "NICO": return "New ICO"
        case "NIG": return "Nigeria"
        case "NKOR": return "Democratic People's Republic of Korea"
        case "NOR": return "Norway"
        case "NPL": return "Federal Democratic Republic of Nepal"
        case "NZ": return "New Zealand"
        case "O3B": return "O3b Networks"
        case "ORB": return "ORBCOMM"
        case "PAKI": return "Pakistan"
        case "PERU": return "Peru"
        case "POL": return "Poland"
        case "POR": return "Portugal"
        case "PRC": return "People's Republic of China"
        case "PRY": return "Republic of Paraguay"
        case "PRES": return "People's Republic of China/European Space Agency"
        case "QAT": return "State of Qatar"
        case "RASC": return "RascomStar-QAF"
        case "ROC": return "Taiwan (Republic of China)"
        case "ROM": return "Romania"
        case "RP": return "Philippines (Republic of the Philippines)"
        case "RWA": return "Republic of Rwanda"
        case "SAFR": return "South Africa"
        case "SAUD": return "Saudi Arabia"
        case "SDN": return "Republic of Sudan"
        case "SEAL": return "Sea Launch"
        case "SES": return "SES"
        case "SGJP": return "Singapore/Japan"
        case "SING": return "Singapore"
        case "SKOR": return "Republic of Korea"
        case "SPN": return "Spain"
        case "STCT": return "Singapore/Taiwan"
        case "SVN": return "Slovenia"
        case "SWED": return "Sweden"
        case "SWTZ": return "Switzerland"
        case "TBD": return "To Be Determined"
        case "THAI": return "Thailand"
        case "TMMC": return "Turkmenistan/Monaco"
        case "TUN": return "Republic of Tunisia"
        case "TURK": return "Turkey"
        case "UAE": return "United Arab Emirates"
        case "UK": return "United Kingdom"
        case "UKR": return "Ukraine"
        case "UNK": return "Unknown"
        case "URY": return "Uruguay"
        case "US": return "United States"
        case "USBZ": return "United States/Brazil"
        case "VENZ": return "Venezuela"
        case "VTNM": return "Vietnam"
        default:
            return nil
        }
    }
}

extension Owner: Equatable {}
